- name: test my new module
  hosts: localhost
  tasks:

  - name: run the new module check_mode
    my_test:
      name: 'hello'
      new: True
    register: testout
    check_mode: True

  - name: dump test output check_mode
    debug:
      msg: '{{ testout }}'

  - name: run the module
    my_test:
      name: 'hello'
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'


  - name: run the new module
    my_test:
      name: 'hello'
      new: True
    register: testout
  - name: dump test output
    debug:
      msg: '{{ testout }}'

  - name: fail my_test
    my_test:
      name: 'fail me'
    ignore_errors: true